## Camunda Helm chart.
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    tag:

  identity:
    auth:
      # Disable Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false


optimize:
  enabled: true

console:
  # Camunda Enterprise repository.
  # https://hub.docker.com/r/camunda/console/tags
  image:
    tag: 8.6.10

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  enabled: true
  inbound:
    mode: "disabled"
  image:
    repository: camunda/connectors-bundle
    tag: 8.6.4

operate:
  # https://hub.docker.com/r/camunda/operate/tags
  image:
    tag: 8.6.3

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.6.2

tasklist:
  # https://hub.docker.com/r/camunda/tasklist/tags
  image:
    repository: camunda/tasklist
    tag: 8.6.5

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi
  image:
    # renovate: datasource=docker depName=camunda/web-modeler-restapi
    tag: 8.6.3

zeebe:
  # https://hub.docker.com/r/camunda/zeebe/tags
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  resources: {}
  initResources: {}
  image:
    repository: camunda/zeebe
    tag: 8.6.5


zeebeGateway:
  # https://hub.docker.com/r/camunda/zeebe/tags
  replicas: 1
  image:
    repository: camunda/zeebe
    tag: 8.6.5

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  enabled: false
  image:
    repository: camunda/identity
    tag: 8.6.5

identityKeycloak:
  # https://hub.docker.com/r/bitnami/keycloak/tags
  enabled: false
  image:
    repository: bitnami/keycloak
    tag: 25.0.6
  postgresql:
    # https://hub.docker.com/r/bitnami/postgresql/tags
    image:
      repository: bitnami/postgresql
      tag: 15.9.0-debian-12-r0

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  resources: {}
  initResources: {}
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  image:
    repository: bitnami/elasticsearch
    tag: 8.15.4

volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 15Gi
